# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Owl House Co.
logo:               # Logo image URL
description:        Art Prints for Sale
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'http://owlhouse.co' # The base hostname & protocol for your site
twitter:            https://twitter.com/owlhouseco
facebook:           https://www.facebook.com/owlhouseco
instagram:          https://www.instagram.com/owlhouse.co
pinterest:          https://www.pinterest.com/owlhouseco

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  billy:
    name:     Billy Tamplin
    bio:      Illustrator and Designer of OwlHouse Co. I love creating art prints and printables.
    gravatar: https://s.gravatar.com/avatar/e9f9dd57309ad53d75bdca557d6fe5c0?s=80
    email:    heyowlhouse@gmail.com
    website:  http://owlhouse.co
    github:   https://github.com/btamps
    twitter:  https://twitter.com/owlhouseco
